Repository chromebot-websites/chromebot.cf, pull requests merged in 2019-12, with the labels that each got.

#469 Update CNAME
  public/CNAME
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#470 Update index.html
  public/index.html
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#471 Update features.js
  src/premade/features.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#472 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#475 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#477 Vila approved
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#478 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#480 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#481 Added badges!
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#484 remove vila's lies
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#485 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#486 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#488 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#490 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#492 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Waiting On Checks

#494 Social
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#495 Reddit
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#498 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#499 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#503 Mobirise = bad
  src/utils/members.js
Labels: ✅ Priority Level: Low, ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#504 Update error.js
  src/pages/error.js
Labels: ✅ Priority Level: Low, ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#505 Updated href
  src/pages/error.js
Labels: ⚠️ Priority Level: Medium, ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#509 Updated README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀✅ ALL: Priority Level Low

#511 Spag
  src/utils/percentBar.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀✅ ALL: Priority Level Low

#513 Added, placeholder href=“google.com”
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, ⤴️PR: Waiting On Reviews, 🔀⚠️ ALL: Priority Level Medium

#516 remove dead badges
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#517 discord bage thing
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#518 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#519 Added jpeg for readme.
  public/images/C06D5AE8-D12A-4426-A589-908644989BE2.jpeg
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#520 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#528 Add misc images
  public/images/chromebot.gif
  public/images/cm.png
  public/images/manager a.png
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, ⤴️PR: Work In Progress

#548 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#550 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#553 Update index.js
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Waiting On Checks, ⤴️PR: Waiting On Reviews, 🔀ALL: Priority Level Medium

#559 Update index.js
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#563 Update index.js
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level High

#564 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#566 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#567 Delete C06D5AE8-D12A-4426-A589-908644989BE2.jpeg
  public/images/C06D5AE8-D12A-4426-A589-908644989BE2.jpeg
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Medium

#571 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#574 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Medium

#575 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Medium

#579 Update index.js
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Medium

#581 Update base.css
  src/css/base.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, ⤴️PR: Waiting On Reviews, 🔀ALL: Priority Level Medium

#584 Update index.js
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#586 Update base.css
  src/css/base.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level High

#588 Add files via upload
  public/images/2AA15818-B987-4253-AA6B-74BBE74173D6.jpeg
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#590 Update index.js
  src/index.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#602 Update index.js
  src/index.js
Labels: ⤴️PR: Can't Be Automerged, ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, ⤴️PR: Work In Progress, 🔀ALL: Priority Level High

#592 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#598 Update manifest.json
  manifest/manifest.json
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#609 Update button.js
  src/utils/button.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Low

#611 Update button.js
  src/utils/button.js
Labels: ⤴️PR: Can't Be Automerged, ⤴️PR: Waiting On Checks

#613 Update index.js
  src/index.js
  src/utils/button.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, 🔀ALL: Priority Level Medium

#596 Create Terms&Conditions.md
  Terms&Conditions.md
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, ⤴️PR: Waiting On Reviews, 🔀ALL: Priority Level High
