Repository chromebot-websites/chromebot.cf, pull requests merged in 2019-06, with the labels that each got.

#86 Fixed Bug (hopefully)
  client/index.js
Labels: bug, fixed

#89 Update index.js
  client/index.js
Labels: bug, enhancement, fixed

#99 set the stage for responsive design
  client/index.js
  css/custom.css
Labels: enhancement

#102 Create issue_label_bot.yaml
  issue_label_bot.yaml
Labels: merge when green

#101 Update custom.css
  css/custom.css
Labels: merge when green

#104 Fix the issue
  css/custom.css
Labels: bug, fixed, merge when green

#105 Update index.js
  client/index.js
Labels: merge when green

#106 Update custom.css
  css/custom.css
Labels: merge when green

#107 Update custom.css
  css/custom.css
Labels: merge when green

#109 Update custom.css
  css/custom.css
Labels: merge when green

#111 Add files via upload
  images/characters/shopkeeper.png
  images/characters/workman.png
  images/favicon192.png
  images/favicon512.png
  images/items/banana peel.png
  images/items/bin.png
  images/items/bolt.png
  images/items/boot.png
  images/items/car manufacturer.png
  images/items/coffee bean.png
  images/items/empty drinks can.png
  images/items/ferrari.png
  images/items/glass shard.png
  images/items/hideous pink teapot.png
  images/items/house.png
  images/items/laptop.png
  images/items/metal piece.png
  images/items/plastic bag.png
  images/items/red paperclip.png
  images/items/rover.png
  images/items/scrapyard.png
  images/items/stick.png
  images/items/tool kit.png
  images/items/trainer.png
  images/items/vw beetle.png
Labels: merge when green

#112 Update custom.css
  css/custom.css
Labels: merge when green

#113 Update custom.css
  css/custom.css
Labels: merge when green

#114 Update custom.css
  css/custom.css
Labels: merge when green

#115 Update custom.css
  client/index.js
  css/custom.css
Labels: merge when green

#116 Update custom.css
  client/index.js
  css/custom.css
Labels: merge when green

#119 Update index.js
  client/index.js
Labels: merge when green

#118 Update index.js
  client/index.js
Labels: merge when green

#120 Update index.js
  client/index.js
Labels: merge when green

#121 Update index.js
  client/index.js
Labels: merge when green

#122 Update custom.css
  css/custom.css
Labels: merge when green

#123 Update index.js
  client/index.js
Labels: merge when green

#124 Update index.js
  client/index.js
Labels: merge when green

#125 Update index.js
  client/index.js
Labels: known issue, merge when green

#126 Update index.js
  client/index.js
Labels: known issue, merge when green

#129 Update custom.css
  css/custom.css
Labels: known issue, merge when green

#131 Update custom.css
  client/index.js
  css/custom.css
Labels: merge when green

#132 Update index.js
  client/index.js
Labels: merge when green

#133 Update index.js
  client/index.js
Labels: merge when green

#134 Update index.js
  client/index.js
Labels: merge when green

#135 Update index.js
  client/index.js
Labels: merge when green

#136 Update index.js
  client/index.js
Labels: merge when green

#137 Update index.js
  client/index.js
Labels: merge when green

#138 Update index.js
  client/index.js
Labels: merge when green

#139 Update index.js
  client/index.js
Labels: merge when green

#140 Update index.js
  client/index.js
Labels: fixed, merge when green

#142 Update index.js
  client/index.js
Labels: bug, fixed, merge when green

#143 Add files via upload
  favicon.ico
Labels: enhancement, merge when green

#144 Update Roles
  client/index.js
Labels: enhancement, merge when green

#145 Update the favicon (again)
  favicon.ico
Labels: enhancement, merge when green

#146 Update custom.css
  css/custom.css
Labels: merge when green

#147 Update staff list
  client/index.js
Labels: merge when green

#148 Update index.js
  client/index.js
Labels: merge when green

#149 Update issue_label_bot.yaml
  issue_label_bot.yaml
Labels: merge when green

#151 Update README.md
  README.md
Labels: merge when green

#163 Remove react scripts
  package.json
Labels: Dependancy Update, merge when green

#166 Update package.json
  package.json
Labels: fixed, merge when green

#168 Update index.js
  client/index.js
Labels: merge when green

#169 Update README.md
  README.md
Labels: merge when green

#170 Update index.js
  README.md
  index.js
Labels: FATAL BUG, bug

#171 Update index.js
  index.js
Labels: FATAL BUG, bug, fixed, merge when green

#172 Update package.json
  package.json
Labels: merge when green

#174 Update .travis.yml
  .travis.yml
Labels: FATAL BUG, fixed

#173 Error catching begins
  .hound.yml
  .nojekyll
  client/index.js
  client/pages/error.js
  client/premade/home.js
  client/utils/button.js
  client/utils/errorBoundaries.js
  client/utils/members.js
Labels: enhancement, merge when green

#177 Update README.md
  README.md
Labels: fixed, merge when green

#180 Update custom.css
  css/custom.css
Labels: merge when green

#183 Update CODEOWNERS
  CODEOWNERS
Labels: merge when green

#184 Added apple iOS support ;)
  index.html
Labels: enhancement, merge when green

#185 Update home.js
  client/premade/home.js
Labels: merge when green

#189 Update home.js
  client/premade/home.js
  client/utils/members.js
Labels: merge when green

#190 I done messed up
  client/pages/error.js
  client/premade/home.js
  client/utils/button.js
  client/utils/errorBoundaries.js
  client/utils/members.js
Labels: FATAL BUG, bug, merge when green

#191 Update index.js
  client/index.js
Labels: merge when green

#192 Update index.js
  client/index.js
Labels: merge when green

#193 Update error.js
  client/pages/error.js
Labels: merge when green

#194 Update custom.css
  css/custom.css
Labels: merge when green

#196 Update custom.css
  client/pages/error.js
  css/custom.css
Labels: merge when green

#199 Update home.js
  client/premade/home.js
  webpack.config.js
Labels: merge when green

#200 Update errorBoundaries.js
  client/premade/home.js
  client/utils/errorBoundaries.js
  client/utils/members.js
Labels: merge when green

#202 Update home.js
  client/premade/home.js
Labels: merge when green

#204 New Labels!
  .mergify.yml
  issue_label_bot.yaml
Labels: ⤴️PR: Enhancement

#197 Update README.md
  README.md
Labels: *️⃣ISSUE: Fixed, ⤴️PR: Merge When Green

#206 Update .mergify.yml
  .mergify.yml
Labels: ⤴️PR: Enhancement, ⤴️PR: Waiting On Reviews

#203 Update members.js
  client/utils/members.js
Labels: ⤴️PR: Merge When Green

#212 Create codelingo.yaml
  .mergify.yml
  codelingo.yaml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#213 Update codelingo.yaml
  codelingo.yaml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#214 remove codelingo
  codelingo.yaml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#215 Create .jshintrc
  .jshintrc
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#208 Update issue_label_bot.yaml
  issue_label_bot.yaml
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#209 Update home.js
  client/premade/home.js
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#211 Create statusPage.js
  client/utils/statusPage.js
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#210 Update README.md
  README.md
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#216 Update home.js
  client/premade/home.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#217 Update README.md
  README.md
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#218 Update .mergify.yml
  .mergify.yml
  renovate.json
Labels: ⤴️PR: Can't Be Automerged, ⤴️PR: Waiting On Checks

#219 Update README.md
  README.md
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Reviews

#220 Update README.md
  README.md
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#224 Create .restyled.yaml
  .restyled.yaml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#221 Update statusPage.js
  client/premade/home.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Work In Progress

#225 Update statusPage.js
  client/premade/home.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#226 Update .mergify.yml
  .mergify.yml
Labels: ⤴️PR: Can't Be Automerged

#227 Update home.js
  client/premade/home.js
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#228 Update status page
  client/premade/home.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#229 Delete .restyled.yaml
  .restyled.yaml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#230 Update .mergify.yml
  .mergify.yml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Style Update

#231 Create .pullapprove.yml
  .pullapprove.yml
Labels: ⤴️PR: Can't Be Automerged

#234 Update .pullapprove.yml
  .pullapprove.yml
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#236 Update .pullapprove.yml
  .pullapprove.yml
Labels: ⤴️PR: Merge When Green

#237 Update .pullapprove.yml
  .pullapprove.yml
Labels: ⤴️PR: Can't Be Automerged, ⤴️PR: Enhancement

#239 Update .pullapprove.yml
  .pullapprove.yml
Labels: ⤴️PR: Merge When Green

#233 Update statusPage.js
  client/utils/statusPage.js
Labels: ⤴️PR: Merge When Green

#252 Update custom.css
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#253 Update statusPage.js
  client/utils/statusPage.js
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#254 Update custom.css
  css/custom.css
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#260 Update statusPage.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#207 Update README.md
  README.md
Labels: ⤴️PR: Can't Be Automerged, ⤴️PR: Work In Progress, 🔀ALL: Invalid

#264 Update package.json
  package.json
Labels: ⤴️PR: Dependancy Update, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks, ⤴️PR: Waiting On Reviews

#265 Update statusPage.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#267 Update custom.css
  client/premade/home.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#269 Update statusPage.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green, ⤴️PR: Waiting On Checks

#272 Update custom.css
  client/premade/home.js
  client/utils/statusPage.js
  css/custom.css
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green

#276 Add files via upload
  images/canaryLogo.png
  images/chromebotLogo.png
Labels: ⤴️PR: Enhancement, ⤴️PR: Merge When Green
